version: "3.9"

services:
  php:
    build: ./docker/php
    container_name: ukrposhta_php
    volumes:
      - ./app:/var/www/app
      - ./storage:/var/www/storage
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: ukrposhta_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: ukrposhta_db
    restart: always
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4'
    environment:
      MYSQL_DATABASE: ukrposhta
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
